FROM ubuntu:23.04

RUN apt update -y
RUN apt install -y python3 python3-pip wget

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt update -y
RUN apt install -y google-chrome-stable

RUN mkdir /work
COPY . /work

WORKDIR /work
RUN pip3 install --break-system-packages selenium chromedriver-autoinstaller

