FROM selenium/node-chrome:4.16.1-20231219

RUN sudo apt-get update -y
RUN sudo apt-get install -y python3 python3-pip

RUN sudo pip3 install selenium

RUN sudo mkdir /work
WORKDIR /work
COPY . /work

